### ISSUE TITLE
Error handling in estimate()

### ISSUE THREAD

**Issue by shuangMoz** [whatwg/storage#38] opened 2016-11-29 13:12 UTC
If there is an exceptional failure inside estimate(), rejecting the promise makes more sense than resolving a promise with useless StorageEstimate. But now we don't reject the promise in estimate() according to the specification.

**Comment by annevk** [comment] 2016-11-29 14:26
So when exactly can this fail? Some kind of OS I/O error?

**Comment by shuangMoz** [comment] 2016-11-30 06:44
I/O error or other unexpected internal error.

**Comment by annevk** [comment] 2016-11-30 13:23
That's still a little vague. How would I reproduce?

@inexorabletash has Chrome encountered this issue?

**Comment by inexorabletash** [comment] 2016-11-30 18:08
Two of the legacy quota APIs in Chrome do support an error callback; tracing through the code the most common uses are in cases that would be out of scope with the new API, e.g. calling from a file: origin or origins not allowed to store data. But we do route failures in the quota system out in a few places, e.g. InvalidAccessError (e.g. if the quota DB can't be initialized) or AbortError (e.g. to pending queries if the back end is shutting down). These aren't tested from script (i.e. we don't plumb through a "nerf the quota back end" testing API). 

I would expect this could happen in other implementations (although some may choose to terminate in the face of such failure - always an option). I'd be in favor of an escape hatch in the spec that if the site storage usage or quota cannot be determined, reject with UnknownError so that implementations do converge on a behavior. For example, I think my estimate() impl in Chrome probably plumbs through the same errors as the legacy APIs since it's really just a promise shim (in C++) over the legacy callback impl; I should probably map those to generic UnknownError.

**Comment by annevk** [comment] 2016-12-07 00:44
I suggest we use `TypeError` then or maybe the generic `Error`. @domenic?

As for how to phrase it, I guess I'll go with "internal error" and maybe give an example.

**Comment by domenic** [comment] 2016-12-07 00:48
TypeError and the "OperationError" and "NotReadableError" DOMException types seem OK.

**Closed** 2016-12-07 19:44 UTC
